### ISSUE TITLE
SAML/PEFIM: SP mapping

### ISSUE THREAD

**Issue by HaToHo** [its-dirg/pefim-proxy#2]
Problem:
In PEFIM the proxy does not disclose the SP's identity to the IDP, but the affiliation to an entity categor (EC) needs to be communicated. To support automated ARPs it is convenient to publish each group of application-side SPs with the same EC as a single IDP-side SP.

The metadata for this SP would differ in the EC and in the entityID (which could have the EC concatenated).

**Comment by HaToHo** [comment]
pefim proxy makes it possible to configure n numbers of SP's with all EC configurations needed for any given setup.

The calling SP will then be mapped to an underlying SP with the same EC configuration. If no match exists can an error be returned or a default SP can be used.

The solution only works with pysaml2 fork on HaToHo.

**Comment by HaToHo** [comment]
Fixed, still only on pysaml2 fork on HaToHo. Please verify and comment/close.

**Comment by rhoerbe** [comment]
works fine. Please close
