### ISSUE TITLE
make Time Zone in logfile configurable

### ISSUE THREAD

**Issue by rhoerbe** [its-dirg/pefim-proxy#7]
Make TZ configurable. The choice should be local vs. UTC.

Rationale: As most servers log to the local TZ, it is easier if all logs use the same TZ.

**Comment by HaToHo** [comment]
Fixed. 

Default is to log with UTC timestamp. No configuration needed.

Can be changed in pefim_server_conf.py with the parameter LOG_UTC.

LOG_UTC = False #Will log localtime
LOC_UTC = True #Will log with UTC

Please verify and close or write a comment if it's not working for you.
